export const CONFIG = {
  TIME_UPDATE_INTERVAL_MS: 1000,
  TIME_AGO_THRESHOLD_MS: 60000,
  SCROLL_SPEED_MIN: 0,
  SCROLL_SPEED_MAX: 120,
  SCROLL_SPEED_DEFAULT: 30,
  TICKER_SPEED_DEFAULT: 25,
  DASHBOARD_REFRESH_MS: 15000,
} as const;
